maintainer: "Nan Xiao"
email: "me@nanx.me"
from: "rocker/tidyverse:latest"
pandoc: false

cran:
  - rmdformats

bioc:
  - AnnotationHub
  - biomaRt
  - Homo.sapiens
  - org.Hs.eg.db
  - BSgenome
  - BSgenome.Hsapiens.UCSC.hg19
  - TxDb.Hsapiens.UCSC.hg19.knownGene
  - TxDb.Athaliana.BioMart.plantsmart22
